# config.yaml
outdir: "/home/yiz188/my_scratch_space/PTA_4442"
fasta_folder: "/n/data1/hms/dbmi/park/yifan/data/ref/v37/split"
mappability_folder_stem: "/n/data1/hms/dbmi/park/yifan/data/ref/mappability/hg19.CRC.100mer."
metadata_path: "/home/yiz188/my_scratch_space/PTA_4442/samples_4442.txt"
bicseq_norm: "/n/data1/hms/dbmi/park/yifan/tools/NBICseq-norm_v0.2.4/NBICseq-norm.pl"
bicseq_seg: "/n/data1/hms/dbmi/park/yifan/tools/NBICseq-seg_v0.7.2/NBICseq-seg.pl"
binsize: 500000
chrom_list: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X", "Y"]
lambda_range: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]

