__default__:
  account: "park"
  partition: "park,short"
  time: "12:00:00"  # HH:MM:SS format
  nodes: 1
  ntasks: 1
  mem: "4G"
  job-name: "hiscanner_{rule}"
  output: "cluster_logs/{rule}-%j.out"
  error: "cluster_logs/{rule}-%j.err"

get_read_pos:
  # Typically lighter on resources but IO-intensive
  time: "4:00:00"
  mem: "4G"
  ntasks: 1
  partition: "park,short"

run_bicseq_norm:
  # More computationally intensive
  time: "12:00:00"
  mem: "16G"
  ntasks: 4
  partition: "park,short"